name: 'AWS S3 Upload Action'
description: 'This action allows you to upload file to AWS S3.'
runs:
  using: docker
  image: Dockerfile
inputs:
  s3_folder:
    description: "The folder that the file will be placed."
  source:
    description: "The file path that the file will be sourced from."
    required: true
  cloudfront_id:
    description: "Cloudfront id"
    required: true
  aws_access_key_id:
    description: "The AWS access id part of your credentials. More info: https://docs.aws.amazon.com/cli/latest/reference/configure/"
    required: true
  aws_secret_access_key:
    description: "The AWS access key part of your credentials. More info: https://docs.aws.amazon.com/cli/latest/reference/configure/"
    required: true
  target_aws_access_key_id:
    description: "The target AWS access id part of your credentials. More info: https://docs.aws.amazon.com/cli/latest/reference/configure/"
    required: false
  target_aws_secret_access_key:
    description: "The target AWS access key part of your credentials. More info: https://docs.aws.amazon.com/cli/latest/reference/configure/"
    required: false
  aws_region:
    description: "This is the region of the bucket. S3 namespace is global but the bucket is regional."
    required: true
  upload_from:
    description:  "The upload file from local or s3"
    required: true
